version: "3.8"

services:
  tf2:
    image: cm2network/tf2
    environment:
      - SRCDS_TOKEN=<replaceme_token> #you can find this http://steamcommunity.com/dev/managegameservers
      - SRCDS_RCONPW=<replaceme_remote_pwd>
      - SRCDS_PW=<replaceme_pwd>
      - SRCDS_PORT=27015
      - SRCDS_TV_PORT=27020
      - SRCDS_NET_PUBLIC_ADDRESS=0
      - SRCDS_IP=0
      - SRCDS_FPSMAX=300
      - SRCDS_TICKRATE=66
      - SRCDS_MAXPLAYERS=32
      - SRCDS_REGION=3
      - SRCDS_HOSTNAME=<replaceme_name>
      - SRCDS_WORKSHOP_START_MAP=0
      - SRCDS_HOST_WORKSHOP_COLLECTION=0
      - SRCDS_WORKSHOP_AUTHKEY=""
    network_mode: "host"
